# Config file for automatic testing at travis-ci.org
language: python

dist: xenial
sudo: required

python:
  - "3.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "2.7"
  - "pypy"

env:
  - NSQ_VERSION=0.3.5 GO_VERSION=1.4.2
  - NSQ_VERSION=0.3.6 GO_VERSION=1.5.1
  - NSQ_VERSION=0.3.7 GO_VERSION=1.6
  - NSQ_VERSION=0.3.8 GO_VERSION=1.6.2
  - NSQ_VERSION=1.0.0-compat GO_VERSION=1.8

matrix:
  include:
    - env: TOXENV=docs
    - env: TOXENV=lint

install:
  - sudo apt-get install libsnappy-dev
  - pip install -U tox tox-travis
  - bash ./tests/install-nsq.sh

script: tox
